# game config
PLANE_SIZE = 15

# data generation config
NUMBER_of_BATCHES_FOR_EACH_PROCESS = 30
MAX_SIMULATION_WHEN_GENERATING_DATA = 320
NUMBER_of_GAMES_IN_EACH_BATCH = 30
NUMBER_of_SAMPLES_IN_EACH_GAME = 15
GPU_WHEN_GENERATING_DATA = "3"

# training
NUMBER_of_UPDATE_NEURAL_NETWORK = 300
NUMBER_of_BATTLES_WHEN_EVALUATING = 10
MAX_SIMULATION_WHEN_EVALUATING = 80
MIN_BATCH = 120  # number_of_games_for_each_process*number_of_samples_in_each_game*8/min_batch 应该是整数
GPU_WHEN_TRAINING = "4"
START_ITERATION = 1

# monte carlo tree search
C_PUCT = 5.0

# neural network
LEARNING_RATE = 0.0005
L2_REG = 0.005


