# game config
PLANE_SIZE = 8

# data generation config
NUMBER_of_BATCHES_FOR_EACH_PROCESS = 3
MAX_SIMULATION_WHEN_GENERATING_DATA = 10
NUMBER_of_GAMES_IN_EACH_BATCH = 3
NUMBER_of_SAMPLES_IN_EACH_GAME = 6
GPU_WHEN_GENERATING_DATA = "3"

# training
NUMBER_of_UPDATE_NEURAL_NETWORK = 10
NUMBER_of_BATTLES_WHEN_EVALUATING = 10
NUMBER_of_EPOCH = 1
MAX_SIMULATION_WHEN_EVALUATING = 3
MIN_BATCH = 3  # number_of_games_for_each_process*number_of_samples_in_each_game*8/min_batch 应该是整数
GPU_WHEN_TRAINING = "4"
START_ITERATION = 1
KL_TARGET = 0.00002
LEARNING_RATE_MULTI = 1.0

# monte carlo tree search
C_PUCT = 5.0

# neural network
LEARNING_RATE = 0.001
L2_REG = 0.0001


